### PR TITLE
Changes to follow PSR2 coding standard

### PR DESCRIPTION
**Pull request by minterior**
Fixed with script php-cs-fixer (latest commit) (https://github.com/FriendsOfPHP/PHP-CS-Fixer).
Checked with PHP_CodeSniffer version 2.1.1.

### CODE REVIEW

**Comment by ruudk** [comment]
Thanks for this. Can you please rebase with master so that I can automatically merge this with Github? :)

**Comment by minterior** [comment]
Done :)

**Comment by ruudk** [comment]
Thanks!

**Comment by minterior** [comment]
:+1:

**Pull request merged**
